services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/MyBlog
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/MyBlog/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
volumes:
  bundle_data:
  node_modules:
